import '@lixi/components/base/style/css'
import '@lixi/theme-chalk/el-transfer.css'
import '@lixi/components/input/style/css'
import '@lixi/components/button/style/css'
import '@lixi/components/checkbox/style/css'
import '@lixi/components/checkbox-group/style/css'
