import '@lixi/components/base/style'
import '@lixi/theme-chalk/src/transfer.scss'
import '@lixi/components/input/style/index'
import '@lixi/components/button/style/index'
import '@lixi/components/checkbox/style/index'
import '@lixi/components/checkbox-group/style/index'
