import '@lixi/components/base/style'
import '@lixi/theme-chalk/src/time-select.scss'
import '@lixi/components/scrollbar/style/index'
import '@lixi/components/popper/style/index'
import '@lixi/components/input/style/index'
import '@lixi/components/select/style/index'
import '@lixi/components/option/style/index'
