import '@lixi/components/base/style/css'
import '@lixi/theme-chalk/el-table.css'
import '@lixi/components/checkbox/style/css'
import '@lixi/components/tag/style/css'
import '@lixi/components/tooltip/style/css'
