import '@lixi/components/base/style'
import '@lixi/theme-chalk/src/table.scss'
import '@lixi/components/checkbox/style/index'
import '@lixi/components/tag/style/index'
import '@lixi/components/tooltip/style/index'
