import '@lixi/components/base/style'
import '@lixi/theme-chalk/src/cascader-panel.scss'
import '@lixi/components/checkbox/style/index'
import '@lixi/components/radio/style/index'
import '@lixi/components/scrollbar/style/index'
