import '@lixi/components/base/style'
import '@lixi/components/input/style/index'
import '@lixi/components/tag/style/index'
import '@lixi/components/scrollbar/style/index'
import '@lixi/components/popper/style/index'
import '@lixi/theme-chalk/src/select-v2.scss'
