import '@lixi/components/base/style/css'
import '@lixi/theme-chalk/el-message-box.css'
import '@lixi/components/button/style/css'
import '@lixi/components/input/style/css'
import '@lixi/components/overlay/style/css'
